# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://sh-cynosdbmysql-grp-e2g25xa4.sql.tencentcdb.com:26753/yupao?useSSL=false'
    username: root
    password: "010622wjAdm"
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0